src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Table(name="t_event",
 *     uniqueConstraints={@ORM\UniqueConstraint(name="workspace_event_name", columns={"workspace_id", "name"})})
 * @ORM\Entity(repositoryClass=EventRepository::class)
 */
class Event
{
    use TimestampableEntity;

    /**
     * @var int
     *
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @var Workspace
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Workspace", inversedBy="events")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="workspace_id", referencedColumnName="id")
     * })
     */
    protected $workspace;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=150)
     */
    protected $name = '';

    /**
     * @var string
     *
     * @ORM\Column(type="text")
     */
    protected $description = '';

    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     */
    protected $registrationCapacity = 10;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime")
     */
    protected $registrationEndAt;

    /**
     * @var Registration[]|ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="App\Entity\Registration", orphanRemoval=true, mappedBy="event")
     */
    protected $registrations;

    /**
     * Constructor.
     *
     * @param Workspace $workspace
     */
    public function __construct(Workspace $workspace)
    {
        $this->workspace = $workspace;
        $this->workspace->addEvent($this);
        $this->registrationEndAt = date_create('+2 weeks');
        $this->registrations = new ArrayCollection();
    }

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Workspace
     */
    public function getWorkspace(): Workspace
    {
        return $this->workspace;
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name
     *
     * @return static
     */
    public function setName(string $name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return string
     */
    public function getDescription(): string
    {
        return $this->description;
    }

    /**
     * @param string $description
     *
     * @return static
     */
    public function setDescription(string $description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return int
     */
    public function getRegistrationCapacity(): int
    {
        return $this->registrationCapacity;
    }

    /**
     * @param int $registrationCapacity
     *
     * @return static
     */
    public function setRegistrationCapacity(int $registrationCapacity)
    {
        $this->registrationCapacity = $registrationCapacity;

        return $this;
    }

    /**
     * @return int
     */
    public function getRegistrationAvailableCount()
    {
        return max(0, $this->registrationCapacity - $this->registrations->count());
    }

    /**
     * @return \DateTime
     */
    public function getRegistrationEndAt(): \DateTime
    {
        return $this->registrationEndAt;
    }

    /**
     * @param \DateTime $registrationEndAt
     *
     * @return static
     */
    public function setRegistrationEndAt(\DateTime $registrationEndAt)
    {
        $this->registrationEndAt = $registrationEndAt;

        return $this;
    }

    /**
     * Is the registration closed.
     *
     * @return bool
     */
    public function isRegistrationClosed()
    {
        return $this->registrationEndAt < date_create();
    }

    /**
     * Is the registration full.
     *
     * @return bool
     */
    public function isRegistrationFull()
    {
        return $this->registrationCapacity <= $this->registrations->count();
    }

    /**
     * @return Registration[]|ArrayCollection
     */
    public function getRegistrations()
    {
        return $this->registrations;
    }

    /**
     * @param Registration $registration
     *
     * @return static
     */
    public function addRegistrations(Registration $registration)
    {
        $this->registrations[] = $registration;

        return $this;
    }
}

src/Entity/Workspace.php
<?php

namespace App\Entity;

use App\Repository\WorkspaceRepository;
use Ausi\SlugGenerator\SlugGenerator;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Table(name="t_workspace")
 * @ORM\Entity(repositoryClass=WorkspaceRepository::class)
 */
class Workspace
{
    use TimestampableEntity;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=150, unique=true)
     */
    protected $name = '';

    /**
     * @var string
     * @ORM\Column(type="text")
     */
    protected $presentation = '';

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=150, unique=true)
     */
    protected $sluggedName = '';

    /**
     * @var User[]|ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="App\Entity\User", cascade={"persist","remove"}, orphanRemoval=true, inversedBy="workspaces")
     * @ORM\JoinTable(name="t_workspace_user",
     *   joinColumns={
     *     @ORM\JoinColumn(name="workspace_id", referencedColumnName="id")
     *   },
     *   inverseJoinColumns={
     *     @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     *   }
     * )
     */
    protected $users;

    /**
     * @var Event[]|ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="App\Entity\Event", orphanRemoval=true, mappedBy="workspace")
     */
    protected $events;

    /**
     * Constructor.
     */
    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->events = new ArrayCollection();
    }

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name
     *
     * @return Workspace
     */
    public function setName(string $name): self
    {
        $this->name = $name;
        $generator = new SlugGenerator();
        $this->sluggedName = $generator->generate($name);

        return $this;
    }

    /**
     * @return string
     */
    public function getPresentation(): string
    {
        return $this->presentation;
    }

    /**
     * @param string $presentation
     *
     * @return static
     */
    public function setPresentation(string $presentation)
    {
        $this->presentation = $presentation;

        return $this;
    }

    /**
     * @return string
     */
    public function getSluggedName(): string
    {
        return $this->sluggedName;
    }

    /**
     * @return User[]|ArrayCollection
     */
    public function getUsers()
    {
        return $this->users;
    }

    /**
     * @param User $user
     *
     * @return static
     */
    public function addUser(User $user)
    {
        $this->users[] = $user;

        return $this;
    }

    /**
     * @return Event[]|ArrayCollection
     */
    public function getOpenEvents()
    {
        return $this->events->filter(function (Event $event) {return !$event->isRegistrationClosed(); });
    }

    /**
     * @return Event[]|ArrayCollection
     */
    public function getEvents()
    {
        return $this->events;
    }

    /**
     * @param Event $event
     *
     * @return static
     */
    public function addEvent(Event $event)
    {
        $this->events[] = $event;

        return $this;
    }
}

src/Form/WorkspaceType.php
<?php

namespace App\Form;

use App\Entity\Workspace;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class WorkspaceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, ['label' => 'workspace.label.name', 'disabled' => true])
            ->add('sluggedName', TextType::class, ['label' => 'workspace.label.slugged_name', 'disabled' => true])
            ->add('presentation', TextareaType::class, [
                'label' => 'workspace.label.presentation',
                'help' => 'workspace.help.presentation',
                'required' => false,
                'empty_data' => '',
                'attr' => ['rows' => 5],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Workspace::class,
            'translation_domain' => 'forms',
        ]);
    }
}

src/Controller/Admin/WorkspaceController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Workspace;
use App\Form\WorkspaceType;
use App\Security\Voter\WorkspaceVoter;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin")
 */
class WorkspaceController extends AbstractController
{
    /**
     * @Route("/workspace/{sluggedName}/edit", name="admin_workspace_edit")
     * @IsGranted(WorkspaceVoter::EDIT, subject="workspace")
     *
     * @param Request   $request
     * @param Workspace $workspace
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function edit(Request $request, Workspace $workspace)
    {
        $form = $this->createForm(WorkspaceType::class, $workspace);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($workspace);
            $em->flush();
            $this->addFlash('success', 'flash.success.workspace.updated');

            return $this->redirectToRoute('workspace', ['sluggedName' => $workspace->getSluggedName()]);
        }

        return $this->render('admin/workspace/edit.html.twig', [
            'form' => $form->createView(),
            'workspace' => $workspace,
        ]);
    }
}

src/Controller/WorkspaceController.php
<?php

namespace App\Controller;

use App\Entity\Workspace;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class WorkspaceController extends AbstractController
{
    /**
     * @Route("/{sluggedName}", name="workspace")
     *
     * @param Workspace $workspace
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function index(Workspace $workspace)
    {
        return $this->render('workspace/index.html.twig', [
            'controller_name' => 'WorkspaceController',
            'workspace' => $workspace,
        ]);
    }
}

templates/workspace/index.html.twig
{% extends 'layout.html.twig' %}

{% block content_header_title %}{% endblock %}

{% block card_body %}
    <h3>
        {{ 'meta.word.welcome'|trans }} !
        {% if is_granted(constant('App\\Security\\Voter\\WorkspaceVoter::EDIT'), workspace) %}
            <a href="{{ path('admin_workspace_edit', {'sluggedName': workspace.sluggedName}) }}" class="btn btn-primary">
                <i class="fa fa-edit"></i>
                {{ 'meta.word.edit'|trans }}
            </a>
        {% endif %}
    </h3>
    {% if workspace.presentation %}
        <div class="jumbotron">
            {{ workspace.presentation|nl2br }}
        </div>
    {% endif %}

    {% if is_granted(constant('App\\Security\\Voter\\WorkspaceVoter::EDIT'), workspace) %}
        <div class="form-group">
            <label for="workspace-public-link">{{ 'workspace.index.share_link'|trans }}</label>
            <input type="text" class="form-control" id="workspace-public-link"
                   value="{{ url('workspace', {'sluggedName': workspace.sluggedName}) }}"
                   readonly="readonly">
        </div>
    {% endif %}
{% endblock %}

{% block page_content %}
    {{ parent() }}

    {% if not workspace.openEvents.empty %}
        <h4>{{ 'workspace.index.event_list'|trans }}</h4>
    {% else %}
        <h4>{{ 'workspace.index.event_list_empty'|trans }}</h4>
    {% endif %}

    <div class="row">
        {% for event in workspace.openEvents %}
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <h5>{{ event.name }}
                            <span class="badge {% if event.registrationFull %}badge-warning{% else %}badge-success{% endif %} float-right">
                                {{ 'workspace.index.event_registration_available_count'|transchoice(event.registrationAvailableCount, {'%count%':event.registrationAvailableCount}) }}
                            </span>
                        </h5>
                    </div>
                    <div class="card-body">
                        <p class="card-text">{{ event.description|nl2br }}</p>
                        {% if event.registrationFull %}
                            <a href="#" class="btn btn-secondary">
                                <del>{{ 'workspace.index.action.register_to_event'|trans }}</del>
                            </a>
                        {% else %}
                            <a href="{{ path('event_registration_register', {'sluggedName':workspace.sluggedName, 'event':event.id}) }}" class="btn btn-primary">
                                <i class="fa fa-clipboard-list"></i>
                                {{ 'workspace.index.action.register_to_event'|trans }}
                            </a>
                        {% endif %}

                        {% if is_granted(constant('App\\Security\\Voter\\EventVoter::EDIT'), event) %}
                            <a href="{{ path('admin_event_edit', {'sluggedName': workspace.sluggedName, 'event': event.id}) }}" class="btn btn-primary">
                                <i class="fa fa-edit"></i>
                                {{ 'meta.word.edit'|trans }}
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}